# 语言设置
lang: zh_CN

# 最大经验存量
max-stock: 1000

# 施法成功所需的攻击次数
# SHOOT 表示已施法次数，STOCK 表示经验存量，MAXSTOCK表示最大经验存量
required-attack-times: '1.618^SHOOT + 10'

# 每次施法可以射出的经验数额
# SHOOT 表示已施法次数，STOCK 表示经验存量，MAXSTOCK表示最大经验存量
shoot-amount: 'STOCK / 2'

# 经验类型：VANILLA（原版）、SKILLAPI、MMOCORE
exp-type: 'VANILLA'

# 攻击设置
attack:
  # 有效攻击距离（单位：方块）
  distance: 2.0
  # 超时时间（单位tick）
  timeout: 100

# 恢复设置
restore:
  # 施法次数
  shoot:
    # 恢复一次施法次数的时间间隔（单位：tick)
    period: 6000
    # 恢复数量
    amount: 1
  # 经验存量
  stock:
    # 恢复一次经验存量的时间间隔（单位：tick)
    period: 6000
    # 恢复数量
    amount: 200

# 经验物品的自定义模型数据
custom-model-data:
  enable: false
  value: 0

# 音效设置
sound:
  # 攻击时的声音
  attack: 'minecraft:entity.parrot.imitate.slime'
  # 射出时的声音
  shoot: 'minecraft:block.slime_block.step'
  # 没东西射的声音
  shoot-no-exp: 'minecraft:entity.llama.eat'
  # 吃掉经验时的声音
  eat: 'minecraft:entity.player.burp'
