name: ShootEXP
main: moe.feo.shootexp.ShootEXP
version: 1.0
author: Fengshuai(R_Josef)
api-version: 1.16
softdepend:
  - SkillAPI
  - MMOCore
commands:
  shootexp:
    description: 'Main command of ShootEXP'
    usage: '/<command>'
permissions:
  shootexp.*:
    description: 'All permissions.'
    default: op
    children:
      shootexp.item: true
      shootexp.reload: true
  shootexp.item:
    description: 'Get exp item'
    default: op
  shootexp.reload:
    description: 'Reload plugin.'
    default: op
